### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by KleberLeite** [loiane/JogoDaForca#1]
Use nomes em inglês os mesmos devem pronunciáveis e principalmente significativos! E com nomes pronunciáveis você não vai precisar mais comentar várias coisas! Isso ajuda na aparência e leitura do código, e se possível espalhe mais o código em várias classes ao invés de uma só super mega blaster classe ("de pouco em pouco a galinha enche o papo") :P

**Comment by loiane** [comment]
@KleberLeite agradeço as dicas, mas esse código tem mais de 10 anos e foi o primeiro projeto que fiz quando estava aprendendo a programar.
